name: C/C++ CI

env:
  XCA_VERSION: 2.3.0

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'chris2511/xca'
          ref: 'RELEASE.${{ env.XCA_VERSION }}'
          path: 'source'
          fetch-depth: 1

      - name: 'Build XCA'
        run: |
          brew install pkg-config autoconf automake openssl qt libtool
          
          mkdir $GITHUB_WORKSPACE/build
          mkdir $GITHUB_WORKSPACE/install
          cd $GITHUB_WORKSPACE/build
          $GITHUB_WORKSPACE/source/configure --prefix="$GITHUB_WORKSPACE/install" && make install
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ install }}
          path: ${{ install }}
