name: build xca.app

env:
  XCA_VERSION: 2.3.0

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'chris2511/xca'
          ref: 'RELEASE.${{ env.XCA_VERSION }}'
          fetch-depth: 1

      - name: 'Build XCA'
        run: |
          brew install pkg-config autoconf automake openssl qt libtool
          sh bootstrap
          sh configure && make xca.app && tar cvjf xca-$XCA_VERSION.tar.bz2 xca-$XCA_VERSION/xca.app
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: xca.app
          path: 'xca-${{ env.XCA_VERSION }}.tar.bz2'
