name: C/C++ CI

env:
  XCA_VERSION: 2.3.0

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'chris2511/xca'
          ref: 'RELEASE.${{ env.XCA_VERSION }}'
          path: 'source'
          fetch-depth: 1

      - name: 'Build XCA'
        run: |
          brew install pkg-config autoconf automake openssl qt libtool
          
          mkdir build
          mkdir install
          cd build
          ../source/configure --prefix="../install" && make install
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: install
          path: install
